name: Zig

on:
  push:
    branches: [main]
  pull_request:
    branches: ['**']

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: master

      - name: (Zig) Build
        run: zig build --summary new -freference-trace
      - name: Running test
        run: zig build -Denable-tests -Damalgamation test

  # zig-msvc:
  #   runs-on: windows-latest
  #   strategy:
  #     fail-fast: false
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: korandoru/setup-zig@v1
  #       with:
  #         zig-version: master
  #     - name: (Zig) build
  #       run: zig build --summary new -freference-trace -Dtarget=native-windows-msvc
  #     - name: Running test
  #       run: zig build test