name: Zig Cross

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        targets:
          - aarch64-linux-gnu
          - aarch64-linux-musl
          - riscv64-linux-musl
          # LLVM ERROR: Cannot select: 0x7448a42b2fd0: i64 = fp_to_fp16 0x7448a438a570
          # - loongarch64-linux-musl
          - powerpc64-linux-musl
          - powerpc64le-linux-musl

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: master
      # - name: get-flang-linux
      #   run: |
      #       sudo apt-get update
      #       sudo apt-get install --no-install-recommends flang
      - name: Build Summary ${{ matrix.targets }}
        run: zig build --summary all -freference-trace -Dtarget=${{ matrix.targets }}